---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "man/figures/",
  out.width = "100%",
  eval = TRUE,
  warning = FALSE,
  message = FALSE,
  fig.width = 8,
  fig.height = 6
)
# import font ----
if (!requireNamespace('pak')) {
    install.packages('pak', repos = 'https://r-lib.github.io/p/pak/dev/')
}
ext_pkgs <- c('dplyr', 'vroom', 'janitor', 'extrafont', 'sysfonts', 'showtext')
pak::pkg_install(ext_pkgs)
library(extrafont)
extrafont::loadfonts(quiet = TRUE)
extrafont::font_import(
    paths = "inst/assets/Ubuntu/",
    prompt = FALSE)

# add font ----
sysfonts::font_add(
    family =  "Ubuntu", 
    regular = "inst/assets/Ubuntu/Ubuntu-Regular.ttf")

# if necessary: 
# remotes::install_github("yixuan/showtext", force = TRUE)
library(showtext)
# add Arial
sysfonts::font_add("Arial", "/Library/Fonts/Arial.ttf")
showtext::showtext_auto()
```

# segtools

<!-- badges: start -->
<!-- badges: end -->

`segtools` provides the underlying functions and calculations for the [SURVEILLANCE ERROR GRID (SEG)](https://www.diabetestechnology.org/seg.shtml) 

## Installation

You can install the development version of `segtools` from [GitHub](https://github.com/) with:

``` r
# install.packages("devtools")
devtools::install_github("mjfrigaard/segtools")
```

## SEG Graph

The SEG graph can be created from a dataset with `BGM` and `REF` values:

```{r example}
library(segtools)
library(vroom)
# import data
test_data <- vroom::vroom(
  file =
    system.file("extdata", "AppTestData.csv",
        package = "segtools"), delim = ",")
# plot
segtools::seg_grid(
  data = test_data,
  is_path = FALSE,
  alpha_var = 3 / 4,
  size_var = 2.5,
  color_var = "gray85"
)
```

Read more [here](https://www.diabetestechnology.org/seg.shtml).
